theme: jekyll-theme-minimal
title: Beatriz Mayumi
description: Computer Science student at Federal University of ABC (UFABC). Intern at Microsoft Brazil.
[My Lattes CV](http://lattes.cnpq.br/7262131302160585)
[My LinkedIn Profile](https://br.linkedin.com/in/beatrizmatsui)
