theme: jekyll-theme-minimal
title: Beatriz Mayumi
description: Bachelor of Science and Technology. Computer Science student at <a href="http://www.ufabc.edu.br/">Federal University of ABC (UFABC)</a>. Intern at Microsoft Brazil. <br/><br/><a href="http://lattes.cnpq.br/7262131302160585">My Lattes CV</a><br/><br/><a href="https://br.linkedin.com/in/beatrizmatsui">My LinkedIn Profile</a>

